"""Centralized configuration constants for map and world dimensions."""

MAP_WIDTH = 50
MAP_HEIGHT = 30
SCREEN_WIDTH = MAP_WIDTH
SCREEN_HEIGHT = MAP_HEIGHT

WORLD_COLUMNS = 8
WORLD_ROWS = 4
TOTAL_SCREENS = WORLD_COLUMNS * WORLD_ROWS
assert TOTAL_SCREENS == 32
